### ISSUE TITLE
The rest part of the code?

### ISSUE THREAD

**Issue by wukui-muc** [lucidrains/q-transformer#2]
Hi, is this the official implementation of the paper 'Q-Transformer: Scalable Offline Reinforcement
Learning via Autoregressive Q-Functions' ? Could you please upload the rest part of the code? I really appreciate the idea in the paper, I hope to reproduce it recently.

**Comment by lucidrains** [comment]
it is not official

whether i proceed with this project currently depends on a few factors. check back in a month or so
