### ISSUE TITLE
This is the final all code, will it be updated again?

### ISSUE THREAD

**Issue by ltlhuuu** [lucidrains/q-transformer#3]
We are very interested in this work of yours and look forward to further research, and hope you can open source more code from this work! Will it be updated again?

**Comment by lucidrains** [comment]
hey Richard, yes i am very interested in this paper as well

will be building it out this month, tested on lunar lander first

**Comment by lucidrains** [comment]
@ltlhuuu i'm not the author btw

**Comment by lucidrains** [comment]
@ltlhuuu hey, this should be on track to being finished by end of week

would welcome a code review, if you MIT students are planning on building on top of this work.

**Comment by ltlhuuu** [comment]
@lucidrains Yeah, we are supportive of your work and thank you again for your contribution. We will build on this and learn more.
